language: php

php:
  - 5.3
  - 5.4

before_script:
  - cd ..
  - git clone git://github.com/zendframework/ZendSkeletonApplication.git
  - cd ZendSkeletonApplication
  - cp ../OcraLoremModule/.travis/composer.json ./
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - rm -rf vendor/ocramius/ocra-lorem-module
  - cp -r ../OcraLoremModule vendor/ocramius/ocra-lorem-module

script:
  - cd vendor/ocramius/ocra-lorem-module/tests
  - phpunit
